import NavBar from '@/components/navBar/NavBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>store with nextjs</title>
      </head>

      <body>

        {children}
      </body>
    </html>
  )
}
